#!/bin/bash

if [ "$1" == "" ]; then
    echo "Please specify the name of a spec package to build."
    echo "Example: build-spec nginx.spec" 
    echo "This command will look for the spec file in ~/rpmbuild/SPECS"
else
    for SPEC in "$@"
    do
        echo "BUILDING: $SPEC"
        cd ~/rpmbuild
        yum-builddep -y "$SPEC"
        rpmbuild --clean -ba "$SPEC"
        
        # exit if bad return code
        rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi
    done
fi
